config/routes.rb
Rails.application.routes.draw do
 

  get 'homes/index'

  devise_for :users
  resources :user, :controller => "user"
  get 'user', to: 'user#index'
  root 'homes#index'

end

app/models/ability.rb
class Ability
 include CanCan::Ability

  def initialize(user)
   

    user ||= User.new # guest user 

    if user.role == 'pengguna_admin'
      can :manage, :all 
    end

    if user.role == 'pengguna_biasa'
     can :roll, :logs
    end 

  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable


  ROLES = %w[pengguna_admin pengguna_biasa]
	def role?(base_role)
	  ROLES.index(base_role.to_s) <= ROLES.index(role)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter do
  resource = controller_name.singularize.to_sym
  method = "#{resource}_params"
  params[resource] &&= send(method) if respond_to?(method, true)
end 


     
def current_ability
  @current_ability ||= Ability.new(current_user)
end

  rescue_from CanCan::AccessDenied do |exception|
   flash[:error] = exception.message
   if user_signed_in?
   	redirect_to '/'
   else
    redirect_to '/users/sign_in'
	end
  end   
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
 
  def index
  	authorize! :roll, :logs
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
before_action :set_type, only: [:edit, :update, :destroy]
 load_and_authorize_resource
   def index
    @users = User.all
  end  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Successfully created User." 
      redirect_to '/user'
    else
      render :action => 'new'
    end
  end

  def edit 
  end

  def update 
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
    if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully updated User."
 
      redirect_to '/user'
      
    else
      render :action => 'edit'
    end
  end

  def destroy 
    if @user.destroy
      flash[:notice] = "Successfully deleted User."
      redirect_to '/user'
    end
  end 
protected
  def set_type
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email,:password,:role,:password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/homes/index.html.erb
<br>
<h1>Selamat anda Berhasil Akses halaman homes/index</h1> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Appotentikasiuser</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<br>

 
		 <% if user_signed_in? %>
		 	<li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete  %></li>
		 	<br>
		 	<li><%= link_to "homes/index", root_path %></li>
		 	<br> 
		 <% end %>


		 <% if user_signed_in? && current_user.role == 'pengguna_admin'%>
		 	<li><%= link_to "Index User", user_index_path %></li>
		 <% end %>


<%= yield %>
 
</body>
</html>

app/views/user/edit.html.erb
<%= form_for @user, :url => user_path do |f| %>
  
 
<p><%= f.label :email %><br />
<%= f.text_field :email %></p>

<p><%= f.label :password %><br />
<%= f.password_field :password %></p>

<p><%= f.label :password_confirmation %><br />
<%= f.password_field :password_confirmation %></p>

 <%= f.label :Role %><br />
<div>
  <%= f.select :role   do %> 
  <% [['pengguna_admin', 'pengguna_admin'],['pengguna_biasa', 'pengguna_biasa']].each do |c| -%>
    <%= content_tag(:option, c.first, value: c.last) %>
  <% end %>
<% end %><br />

<p><%= f.submit "Submit" %></p>
<% end %>

 

app/views/user/index.html.erb
<h1>Listing User</h1>

<table class="table table-stripped">
  <thead>
    <tr> 
      <th>email</th> 
       <th>role</th> 
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr> 
        <td><%= user.email %></td> 
         <td><%= user.role %></td> 
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
         <td><%= link_to 'Hapus', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New user', new_user_path %>

app/views/user/new.html.erb
<%= form_for @user, :url => user_index_path do |f| %>
   
  
<p><%= f.label :email %><br />
<%= f.text_field :email %></p>

<p><%= f.label :password %><br />
<%= f.password_field :password %></p>

<p><%= f.label :password_confirmation %><br />
<%= f.password_field :password_confirmation %></p>
 
  <%= f.label :Role %><br />
<div>
  <%= f.select :role   do %> 
  <% [['pengguna_admin', 'pengguna_admin'],['pengguna_biasa', 'pengguna_biasa']].each do |c| -%>
    <%= content_tag(:option, c.first, value: c.last) %>
  <% end %>
<% end %><br />
<p><%= f.submit "Submit" %></p>
<% end %>

 